// <auto-generated />
using System;
using IndividualsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IndividualsApi.Migrations
{
    [DbContext(typeof(IndividualsContext))]
    partial class IndividualsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IndividualsApi.Data.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("IndividualsApi.Data.Entities.Individual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("Image");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<string>("PersonalId")
                        .IsRequired()
                        .HasMaxLength(11);

                    b.Property<int>("Sex");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Individuals");
                });

            modelBuilder.Entity("IndividualsApi.Data.Entities.Relation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IndividualId");

                    b.Property<int>("RelativeId");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("IndividualId");

                    b.HasIndex("RelativeId");

                    b.ToTable("Relations");
                });

            modelBuilder.Entity("IndividualsApi.Data.Entities.Individual", b =>
                {
                    b.HasOne("IndividualsApi.Data.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IndividualsApi.Data.Entities.Relation", b =>
                {
                    b.HasOne("IndividualsApi.Data.Entities.Individual", "individual")
                        .WithMany("Relatives")
                        .HasForeignKey("IndividualId");

                    b.HasOne("IndividualsApi.Data.Entities.Individual", "Relative")
                        .WithMany()
                        .HasForeignKey("RelativeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
